name: unique_device_identifier
description: "A Flutter plugin that provides a unique device identifier on all platforms including Android, iOS, Windows, macOS, Linux, Web."
version: 1.0.0

homepage: https://github.com/jonghoon023/unique_device_identifier
repository: https://github.com/jonghoon023/unique_device_identifier
issue_tracker: https://github.com/jonghoon023/unique_device_identifier/issues

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.unique_device_identifier
        pluginClass: UniqueDeviceIdentifierPlugin
      ios:
        pluginClass: UniqueDeviceIdentifierPlugin
      linux:
        pluginClass: UniqueDeviceIdentifierPlugin
      macos:
        pluginClass: UniqueDeviceIdentifierPlugin
      windows:
        pluginClass: UniqueDeviceIdentifierPluginCApi
      web:
        pluginClass: UniqueDeviceIdentifierWeb
        fileName: web/unique_device_identifier_web.dart
